export const DATE_FORMAT = {
  SHORT_MONTH_DAY_YEAR_WITH_COMMA: "MMM dd, yyyy",
  SHORT_MONTH_DAY: "MMM dd",
  MONTH_YEAR: "MMMM yyyy",
  SHORT_MONTH_DAY_COMMA_STANDARD_CLOCK_MERIDIEM: "MMM dd, hh:mm aaa",
} as const;
